collections_config:
  blog:
    name: "Blog Posts"
    files:
      - name: "Blog Posts"
        label: "Blog Posts"
        file: "{{slug}}.md"
        path: "content/blog"
        fields:
          - name: "title"
            label: "Title"
            widget: "string"
          - name: "date"
            label: "Date"
            widget: "datetime"
          - name: "image"
            label: "Image"
            widget: "image"
            media_folder: "static/images/blog" # Folder where images are stored
            public_folder: "/images/blog" # URL path for the images
          - name: "body"
            label: "Body"
            widget: "markdown"
  pages:
    output: true
    icon: notes
    _enabled_editors:
      - visual
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_editables:
  text:
    allow_custom_markup: true
    remove_custom_markup: false
    bold: true
    copyformatting:
    italic: true
    link: true
    paths:
    redo: true
    removeformat:
    strike:
    subscript:
    superscript:
    underline: true
    undo: true
  image:
    expandable: true
    height:
    image_size_attributes: true
    mime_type:
    paths:
      uploads:
      uploads_filename:
      uploads_use_relative_path:
      static:
      dam_uploads:
      dam_uploads_filename:
      dam_static:
    resize_style: contain
    width:
data_config: {}
editor:
  default_path:
timezone: Etc/UTC
