collections_config:
  posts:
    name: "Posts"
    files:
      - name: "Posts"
        label: "Posts"
        file: "{{slug}}.md"
        path: "content/posts"
        fields:
          - name: "title"
            label: "Title"
            widget: "string"
          - name: "date"
            label: "Date"
            widget: "datetime"
          - name: "image"
            label: "Image"
            widget: "image"
            media_folder: "static/images/blog" # Folder where images are stored
            public_folder: "/images/blog" # URL path for the images
          - name: "body"
            label: "Body"
            widget: "markdown"
          - name: "components"
            label: "Components"
            widget: "list"
            types:
              - name: About
                label: "About Section"
                file: "component-library/components/about/about.bookshop.yaml"
              - name: Slider
                label: "Slider Component"
                file: "component-library/components/slider/slider.bookshop.yaml"

pages:
  output: true
  icon: notes
  _enabled_editors:
    - visual
  disable_add: false
  disable_add_folder: false
  disable_file_actions: false

_editables:
  text:
    allow_custom_markup: true
    remove_custom_markup: false
    bold: true
    copyformatting: true
    italic: true
    link: true
    redo: true
    removeformat: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    undo: true
  image:
    expandable: true
    image_size_attributes: true
    paths:
      uploads: "static/images/blog" 
      uploads_filename: "{{slug}}-{{filename}}" 
      uploads_use_relative_path: false
      static: "/images/blog" 
    resize_style: contain

data_config: {}

editor:
  default_path: "content/posts"
timezone: Etc/UTC

components:
  - name: About
    label: "About Section"
    file: "component-library/components/about/about.bookshop.yaml"
  - name: Slider
    label: "Slider Component"
    file: "component-library/components/slider/slider.bookshop.yaml"
