# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Services
  description: Services section
  icon: receipt
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  sections:
    - icon: ""
      title: ""
      text: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  sections:
    - icon: ti-desktop
      title: Our Services
      text: We provide a wide range of creative services
    - icon: ti-desktop
      title: Web development.
      text: A digital agency isn't here to replace your internal team, we're here to
        partner
    - icon: ti-desktop
      title: Interface Design.
      text: A digital agency isn't here to replace your internal team, we're here to
        partner
    - icon: ti-desktop
      title: Business Consulting.
      text: A digital agency isn't here to replace your internal team, we're here to
        partner
    - icon: ti-desktop
      title: Branding.
      text: A digital agency isn't here to replace your internal team, we're here to
        partner
    - icon: ti-desktop
      title: App development.
      text: A digital agency isn't here to replace your internal team, we're here to
        partner
    - icon: ti-desktop
      title: Content creation.
      text: A digital agency isn't here to replace your internal team, we're here to
        partner

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
