# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: testimonial
  description: Testimonial section
  icon: receipt
  tags: []

blueprint:
  title: ""
  header: ""
  sections:
    - icon: ""
      text: ""
      name: ""
      position: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Clients testimonial
  header: Check what's our clients say about us
  sections:
    - icon: ti-desktop
      text:
        Consectetur adipisicing elit. Quam maiores perspiciatis temporibus odio
        reiciendis error alias debitis atque consequuntur natus iusto recusandae
        .
      name: James Watson
      position: Excutive Director,themefisher
    - icon: ti-desktop
      text:
        Consectetur adipisicing elit. Quam maiores perspiciatis temporibus odio
        reiciendis error alias debitis atque consequuntur natus iusto recusandae
        .
      name: James Watson
      position: Excutive Director,themefisher
    - icon: ti-desktop
      text:
        Consectetur adipisicing elit. Quam maiores perspiciatis temporibus odio
        reiciendis error alias debitis atque consequuntur natus iusto recusandae
        .
      name: James Watson
      position: Excutive Director,themefisher
    - icon: ti-desktop
      text:
        Consectetur adipisicing elit. Quam maiores perspiciatis temporibus odio
        reiciendis error alias debitis atque consequuntur natus iusto recusandae
        .
      name: James Watson
      position: Excutive Director,themefisher
    - icon: ti-desktop
      text:
        Consectetur adipisicing elit. Quam maiores perspiciatis temporibus odio
        reiciendis error alias debitis atque consequuntur natus iusto recusandae
        .
      name: James Watson
      position: Excutive Director,themefisher

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
