[component]
structures = ["content_blocks"]
label = "About"
description = "Main page CTA section"
icon = "title"
tags = []


[props]
title = "We create for you"
header = "Entrust Your Project to Our Best Team of Professionals"
subheader = "Have any project on mind? For immidiate support :"
number = "+23 876 65 455"

