spec:
  structures:
    - content_blocks
  label: CTA
  description: CTA section
  icon: title
  tags: []

blueprint:
  title: ""
  header: ""
  subheader: ""
  phone: ""

preview:
  title: we create for you
  header: Entrust your project to our best team of professionals
  subheader: Have any projects in mind? For immediate support,
  phone: "+12 345 67 890"
