[component]
structures = ["content_blocks"]
label = "Counter"
description = "Counter section section"
icon = "receipt"
tags = []

[[props.sections]]
icon = "ti-desktop"
number = "1730"
stat = "Projects Done"

[[props.sections]]
icon = "ti-desktop"
number = "125"
stat = "Users worldwide"

[[props.sections]]
icon = "ti-desktop"
number = "39"
stat = "Available countries"

[[props.sections]]
icon = "ti-desktop"
number = "14"
stat = "Awards Done"

